# Convolutional Neural Networks
CNN's are a type of deep neural network architecture designed specifically for large matrices (specifically images). The fundamental operation inside a CNN are that of convolution, max pooling, and so on. In these sections, we will look at them one by one.

## Convolution
Convolution is an important multiplication operation used videly in signal processing, image processing, machine learning, and other areas. The multiplication between two arrays $f$ and $g$ would be expressed as:

$\displaystyle C(i) = \sum_j f(j) g(i - j)$

Usually, $f$ is considered as an input function (in our case, an image), and $g$ is considered as a gaussian filter or kernel. Both $i$ and $j$ are index points to move across the arrays. There are variations to this formula which manipulate the directions of index point movements. Some behave like forward convolution, others as backwards convolution. Examples are:

$\displaystyle C(i) = \sum_j f(j) g(i + j)$

$\displaystyle C(i) = \sum_j f(i - j) g(j)$

and so on. This is so that there is alignment between $f$ and kernel $g$ while sliding across the input. Note that this means that there may be convolutions aligned to middle/center also. So, considering a case of $f = [1, 2, 3, 4, 5]$, and $g = [1, 0, -1]$. For $g$ to slide across $f$ values of $1, 2, 3$, followed by $2, 3, 4$, and lastly $3, 4, 5$, we would use:

$\displaystyle C(i) = \sum_j f(i + j) g(j)$

This wold give:

$\displaystyle C[0] = f[0+0] g[0] + f[0+1] g[1] + f[0+2] g[2] = f[0]g[0] + f[1]g[1] + f[2]g[2]$

$\displaystyle C[1] = f[1+0] g[0] + f[1+1] g[1] + f[1+2] g[2] = f[1]g[0] + f[2]g[1] + f[3]g[2]$

$\displaystyle C[2] = f[2+0] g[0] + f[2+1] g[1] + f[2+2] g[2] = f[2]g[0] + f[3]g[1] + f[4]g[2]$

What the convolution captures in the positions $C[0]$, $C[1]$, and $C[2]$ are patterns, edges, textures, or specific features within the input $f$ which are amplified or highlighted on the basis of kernel $g$. 

## Padding

Alternatively, if we use:

$\displaystyle C(i) = \sum_j f(i - j) g(j)$

We would have:

$\displaystyle C[0] = f[0-0] g[0] + f[0-1] g[1] + f[0-2] g[2] = f[0]g[0] + f[-1]g[1] + f[-2]g[2]$

$\displaystyle C[1] = f[1-0] g[0] + f[1-1] g[1] + f[1-2] g[2] = f[1]g[0] + f[0]g[1] + f[-1]g[2]$

$\displaystyle C[2] = f[2-0] g[0] + f[2-1] g[1] + f[2-2] g[2] = f[2]g[0] + f[1]g[1] + f[0]g[2]$

Due to the negative indexing of $f[-1]$ and $f[-2]$, we would require to apply left side padding to become $f = [0, 0, 1, 2, 3, 4, 5]$. This would also mean that to span all the array element, we would additionally need:

$\displaystyle C[3] = f[3-0] g[0] + f[3-1] g[1] + f[3-2] g[2] = f[3]g[0] + f[2]g[1] + f[1]g[2]$

$\displaystyle C[4] = f[4-0] g[0] + f[4-1] g[1] + f[4-2] g[2] = f[4]g[0] + f[3]g[1] + f[2]g[2]$

So, padding is simply the inclusion of some 0 values to the left $P_l$, right $P_r$, or both sides of an array $P$. In CNN, usually $P$ is considered. So $P = 2$ would mean that an image would be padded with two zeros in all 4 sides of an image. 

## Strides

In the above cases, the index positions move by a distance of 1 across the array values. This is called 1-stride or $S = 1$. Occassionally, we would want it to move across 2 positions, or even larger positions. Why would we do it? To help capture local features, or global features. This also helps in speeding things up. 

## Output Size

When a convolution is processed, the output size $S_c$ of the convolved can be determined from the following:

$\displaystyle S_c = \frac{S_f - S_g + 2 P}{S} + 1$

## Convolution, Padding, Strides in Higher Dimensions

The explanation given in previous sections applies to convolution in 1D. In the case of images or matrices, the same logic can be extended to y-axis to get Convolution in 2D. In the case of 2D convolution, we would have:

$\displaystyle C(i, j) = \sum_m \sum_n f (i + m, j + n) g (m, n)$

As an example, consider a 3×3 image $f$ and a 2×2 kernel $g$:

$f =
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

$g =
\begin{bmatrix}
1 & 0 \\
0 & -1
\end{bmatrix}
$

The convolution outputs would be:

$C(0,0) = (1 \times 1) + (2 \times 0) + (4 \times 0) + (5 \times -1) = 1 + 0 + 0 - 5 = -4$

$C(1,0) = (2 \times 1) + (3 \times 0) + (5 \times 0) + (6 \times -1) = 2 + 0 + 0 - 6 = -4$

$C(0,1) = (4 \times 1) + (5 \times 0) + (7 \times 0) + (8 \times -1) = 4 + 0 + 0 - 8 = -4$

$C(1,1) = (5 \times 1) + (6 \times 0) + (8 \times 0) + (9 \times -1) = 5 + 0 + 0 - 9 = -4$

Likewise, padding and striding would also be applied along both x and y axis. 

The output size would then be:

$\displaystyle (S_c^x, S_c^y)= \left(\frac{S_f^x - S_g^x + 2 P^x}{S^x} + 1, \frac{S_f^y - S_g^y + 2 P^y}{S^y} + 1\right)$

In the following, some code to help calculate these are provided:

## Kernels

Kernels (or filters) are small matrices that slide over an image to perform feature extraction in image processing and deep learning. Different kernels emphasize different properties like edges, blurring, or sharpening.

As an example, the following will leave an image unchanged:

$
\begin{bmatrix}
0 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 0
\end{bmatrix}
$

For identifying vertical edges, we may use $K_v$ and $K_h$ (Prewitt filters):

$K_v = \begin{bmatrix}
-1 & 0 & 1 \\
-1 & 0 & 1 \\
-1 & 0 & 1
\end{bmatrix}, K_h = \begin{bmatrix}
-1 & -1 & -1 \\
0 & 0 & 0\\
1 & 1 & 1
\end{bmatrix}$

To do the same activity, with more emphasis on central pixels, a variation (Sobel filters) can be used:

$K_v = 
\begin{bmatrix}
-1 & 0 & 1 \\
-2 & 0 & 2 \\
-1 & 0 & 1
\end{bmatrix}, K_h = 
\begin{bmatrix}
-1 & -2 & -1 \\
0 & 0 & 0 \\
1 & 2 & 1
\end{bmatrix}$

For both directions, we may use the Laplacian filters:

$\begin{bmatrix}
0 & 1 & 0 \\
1 & -4 & 1 \\
0 & 1 & 0
\end{bmatrix}, \text{or} \begin{bmatrix}
1 & 1 & 1 \\
1 & -8 & 1 \\
1 & 1 & 1
\end{bmatrix}$

For sharpening an image, we may have:

$\begin{bmatrix}
0 & -1 & 0 \\
-1 & 5 & -1 \\
0 & -1 & 0
\end{bmatrix}
$

For blurring an image, we may have:

$\frac{1}{9}
\begin{bmatrix}
1 & 1 & 1 \\
1 & 1 & 1 \\
1 & 1 & 1
\end{bmatrix}
$

or the following as a Gaussian blur, which will have a more smoothening effect:

$\frac{1}{16}
\begin{bmatrix}
1 & 2 & 1 \\
2 & 4 & 2 \\
1 & 2 & 1
\end{bmatrix}
$

There are several other examples which will be mostly covered in a course on digital image processing. In the case of Convolution Neural Networks, we can start with a random kernel and the idea would be that the learning phase of the architecture will come up with any type of kernel. Some kernels may not even have a name.

# CNN Architectures

A typical CNN consists of the following layers:

## Convolution Layer

This is the core building block of a CNN. It applies filters (kernels) to extract meaningful features such as edges, textures, and patterns. Each filter slides over the image, performing element-wise multiplication and summing the results (convolution operation). The result is called a feature map.

In [225]:
import numpy as np

def conv2d(image, kernel):
    kernel_height, kernel_width = kernel.shape
    image_height, image_width = image.shape
    output_height = image_height - kernel_height + 1
    output_width = image_width - kernel_width + 1
    output = np.zeros((output_height, output_width))
    
    for i in range(output_height):
        for j in range(output_width):
            region = image[i:i+kernel_height, j:j+kernel_width]
            output[i, j] = np.sum(region * kernel)
    
    return output

After convolution layer, a ReLU (Rectified Linear Unit) activation function is applied

In [226]:
def relu(x):
    return np.maximum(0, x)

## Pooling Layer

Pooling layers reduce the spatial dimensions while retaining important information. The most common types are **Max Pooling**, which takes the maximum value from each region, and **Average Pooling**, which takes the average value from the same region. Pooling helps in reducing the computation as well as controls overfitting. 

In [227]:
def max_pooling(image, pool_size=2):
    image_height, image_width = image.shape

    output_height = (image_height + pool_size - 1) // pool_size
    output_width = (image_width + pool_size - 1) // pool_size
    output = np.zeros((output_height, output_width))

    for i in range(output_height):
        for j in range(output_width):
            start_i = i * pool_size
            start_j = j * pool_size
            end_i = min(start_i + pool_size, image_height)
            end_j = min(start_j + pool_size, image_width)

            region = image[start_i:end_i, start_j:end_j]
            output[i, j] = np.max(region)

    return output

def avg_pooling(image, pool_size=2):
    image_height, image_width = image.shape

    output_height = (image_height + pool_size - 1) // pool_size
    output_width = (image_width + pool_size - 1) // pool_size
    output = np.zeros((output_height, output_width))

    for i in range(output_height):
        for j in range(output_width):
            start_i = i * pool_size
            start_j = j * pool_size
            end_i = min(start_i + pool_size, image_height)
            end_j = min(start_j + pool_size, image_width)

            region = image[start_i:end_i, start_j:end_j]
            output[i, j] = np.average(region)

    return output

## Fully Connected Dense Layer

After feature extraction, the output is flattened and passed through fully connected layers, where each neuron is connected to every neuron in the next layer. The output of this layer is the application of the softmax activation function. 

In [228]:
def dense_layer(inputs, weights, bias):
    return np.dot(inputs, weights) + bias

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)


# Working Example

## Input Data

We start with an example 5x5 image representing some numbers given in binary. 

In [229]:
image = np.array([
    [0, 1, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 1, 1, 1, 0]
])

kernel = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [1, 0, 1]
]).astype(np.float64)

## Convolution Layer

In [230]:
conv_output = conv2d(image, kernel)
print("Convolution Output:\n", conv_output)

Convolution Output:
 [[1. 2. 1.]
 [0. 2. 0.]
 [1. 2. 1.]]


In [231]:
relu_output = relu(conv_output)
print("\nReLU Output:\n", relu_output)


ReLU Output:
 [[1. 2. 1.]
 [0. 2. 0.]
 [1. 2. 1.]]


## Max Pooling Layer

In [232]:
pool_output = max_pooling(relu_output)
print("\nMax Pooling Output:\n", pool_output)


Max Pooling Output:
 [[2. 1.]
 [2. 1.]]


## Fully Dense Layer

In [242]:
flattened = pool_output.flatten()

fc_weights = np.random.randn(len(flattened), 10)*0.01
fc_bias = np.random.randn(10)*0.01

dense_output = dense_layer(flattened, fc_weights, fc_bias)
print("\nFully Connected Layer Output:\n", dense_output)


Fully Connected Layer Output:
 [ 0.05802171 -0.00893779  0.06423701 -0.05868947 -0.01187308  0.00291787
 -0.03199532  0.0389161   0.01085836  0.00250945]


In [243]:
softmax_output = softmax(dense_output)
print("\nSoftmax Output (Probabilities):\n", softmax_output)


Softmax Output (Probabilities):
 [0.10520655 0.09839264 0.10586247 0.09361722 0.09810425 0.09956609
 0.0961499  0.10321559 0.10035984 0.09952544]


The higher value of the softmax will mean that an input image belongs to that particular class. 

# Kernel Feature Learning
Lets assume that the input image provided belongs to either labels 0, 1, 2, 3, 4, 5, 6, 7, 8, or 9. For this, we create a one-hot encoding target class for 8 (if 8 is provided).

In [244]:
print(image)
label = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0]) 

[[0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]]


In [245]:
epochs = 50
learning_rate = 0.01
for epoch in range(epochs):
    # Forward
    feature_map  = conv2d(image, kernel)
    activated    = relu(feature_map)
    pooled       = max_pooling(activated, pool_size=2)
    flattened    = pooled.flatten()
    dense_output = dense_layer(flattened, fc_weights, fc_bias)
    output_layer = softmax(dense_output)

    loss_gradient = output_layer - label
        
    #fc_weights_gradient = np.outer(flattened, loss_gradient)
    fc_weights_gradient = np.dot(flattened[:, np.newaxis], loss_gradient[np.newaxis, :])
    fc_bias_gradient    = loss_gradient
    flattened_gradient  = np.dot(fc_weights, loss_gradient)

    # Reshape for pooling layer
    pooled_gradient = flattened_gradient.reshape(pooled.shape)
    
    # Backprop through max pooling
    feature_map_gradient = np.zeros_like(activated)
    for i in range(pooled.shape[0]):
        for j in range(pooled.shape[1]):
            max_val = pooled[i, j]
            for m in range(2):
                for n in range(2):
                    orig_x, orig_y = i*2 + m, j*2 + n
                    if orig_x < activated.shape[0] and orig_y < activated.shape[1]:  # Check bounds
                        if activated[orig_x, orig_y] == max_val:
                            feature_map_gradient[orig_x, orig_y] = pooled_gradient[i, j]

    
    # Backprop through ReLU
    feature_map_gradient *= np.where(feature_map > 0, 1, 0)
    
    # Backprop through convolution
    kernel_gradient = np.zeros_like(kernel)
    for i in range(kernel.shape[0]):
        for j in range(kernel.shape[1]):
            kernel_gradient[i, j] = np.sum(image[i:i+feature_map.shape[0], j:j+feature_map.shape[1]] * feature_map_gradient)
    
    # Update weights
    fc_weights -= learning_rate * fc_weights_gradient
    fc_bias -= learning_rate * fc_bias_gradient
    kernel -= learning_rate * kernel_gradient

    loss = -np.sum(label * np.log(output_layer + 1e-9))
    print(f"Epoch {epoch+1}, Loss: {loss:.4f}")

print("Updated Kernel:", kernel)
output_layer

Epoch 1, Loss: 2.2946
Epoch 2, Loss: 2.2702
Epoch 3, Loss: 2.2460
Epoch 4, Loss: 2.2216
Epoch 5, Loss: 2.1972
Epoch 6, Loss: 2.1726
Epoch 7, Loss: 2.1478
Epoch 8, Loss: 2.1226
Epoch 9, Loss: 2.0969
Epoch 10, Loss: 2.0708
Epoch 11, Loss: 2.0441
Epoch 12, Loss: 2.0168
Epoch 13, Loss: 1.9888
Epoch 14, Loss: 1.9600
Epoch 15, Loss: 1.9304
Epoch 16, Loss: 1.8998
Epoch 17, Loss: 1.8683
Epoch 18, Loss: 1.8357
Epoch 19, Loss: 1.8020
Epoch 20, Loss: 1.7672
Epoch 21, Loss: 1.7313
Epoch 22, Loss: 1.6940
Epoch 23, Loss: 1.6556
Epoch 24, Loss: 1.6158
Epoch 25, Loss: 1.5748
Epoch 26, Loss: 1.5325
Epoch 27, Loss: 1.4890
Epoch 28, Loss: 1.4442
Epoch 29, Loss: 1.3983
Epoch 30, Loss: 1.3514
Epoch 31, Loss: 1.3035
Epoch 32, Loss: 1.2548
Epoch 33, Loss: 1.2054
Epoch 34, Loss: 1.1555
Epoch 35, Loss: 1.1054
Epoch 36, Loss: 1.0552
Epoch 37, Loss: 1.0052
Epoch 38, Loss: 0.9555
Epoch 39, Loss: 0.9066
Epoch 40, Loss: 0.8585
Epoch 41, Loss: 0.8116
Epoch 42, Loss: 0.7660
Epoch 43, Loss: 0.7220
Epoch 44, Loss: 0.67

array([0.04311831, 0.04190594, 0.04260944, 0.03982661, 0.04103404,
       0.04115852, 0.04008135, 0.04218675, 0.62644565, 0.0416334 ])

# Extending to Multiple Images

In [258]:
dataset = [
    np.array([
        [0, 1, 1, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 0, 1, 0],
        [0, 1, 1, 1, 0]
    ]),
    np.array([
        [0, 1, 1, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 1, 1, 0]
    ])
]

labels = [
    np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),  # Label for first image
    np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),  # Label for second image
]


In [259]:
epochs = 50
learning_rate = 0.01
for epoch in range(epochs):
    total_loss = 0
    for img, label in zip(dataset, labels):
        
        # Forward
        feature_map  = conv2d(img, kernel)
        activated    = relu(feature_map)
        pooled       = max_pooling(activated, pool_size=2)
        flattened    = pooled.flatten()
        dense_output = dense_layer(flattened, fc_weights, fc_bias)
        output_layer = softmax(dense_output)

        loss_gradient = output_layer - label
        
        #fc_weights_gradient = np.outer(flattened, loss_gradient)
        fc_weights_gradient = np.dot(flattened[:, np.newaxis], loss_gradient[np.newaxis, :])
        fc_bias_gradient    = loss_gradient
        flattened_gradient  = np.dot(fc_weights, loss_gradient)

        # Reshape for pooling layer
        pooled_gradient = flattened_gradient.reshape(pooled.shape)
    
        # Backprop through max pooling
        feature_map_gradient = np.zeros_like(activated)
        for i in range(pooled.shape[0]):
            for j in range(pooled.shape[1]):
                max_val = pooled[i, j]
                for m in range(2):
                    for n in range(2):
                        orig_x, orig_y = i*2 + m, j*2 + n
                        if orig_x < activated.shape[0] and orig_y < activated.shape[1]:  # Check bounds
                            if activated[orig_x, orig_y] == max_val:
                                feature_map_gradient[orig_x, orig_y] = pooled_gradient[i, j]

    
        # Backprop through ReLU
        feature_map_gradient *= np.where(feature_map > 0, 1, 0)
    
        # Backprop through convolution
        kernel_gradient = np.zeros_like(kernel)
        for i in range(kernel.shape[0]):
            for j in range(kernel.shape[1]):
                kernel_gradient[i, j] = np.sum(image[i:i+feature_map.shape[0], j:j+feature_map.shape[1]] * feature_map_gradient)
    
        # Update weights
        fc_weights -= learning_rate * fc_weights_gradient
        fc_bias -= learning_rate * fc_bias_gradient
        kernel -= learning_rate * kernel_gradient

        loss = -np.sum(label * np.log(output_layer + 1e-9))
        total_loss += loss
    
    avg_loss = total_loss / len(dataset)
    print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

print("Updated Kernel:", kernel)

Epoch 1, Loss: 0.4218
Epoch 2, Loss: 0.3993
Epoch 3, Loss: 0.3850
Epoch 4, Loss: 0.3749
Epoch 5, Loss: 0.3673
Epoch 6, Loss: 0.3609
Epoch 7, Loss: 0.3554
Epoch 8, Loss: 0.3503
Epoch 9, Loss: 0.3455
Epoch 10, Loss: 0.3410
Epoch 11, Loss: 0.3366
Epoch 12, Loss: 0.3323
Epoch 13, Loss: 0.3281
Epoch 14, Loss: 0.3240
Epoch 15, Loss: 0.3199
Epoch 16, Loss: 0.3159
Epoch 17, Loss: 0.3119
Epoch 18, Loss: 0.3080
Epoch 19, Loss: 0.3041
Epoch 20, Loss: 0.3003
Epoch 21, Loss: 0.2965
Epoch 22, Loss: 0.2927
Epoch 23, Loss: 0.2890
Epoch 24, Loss: 0.2853
Epoch 25, Loss: 0.2816
Epoch 26, Loss: 0.2780
Epoch 27, Loss: 0.2745
Epoch 28, Loss: 0.2709
Epoch 29, Loss: 0.2674
Epoch 30, Loss: 0.2640
Epoch 31, Loss: 0.2606
Epoch 32, Loss: 0.2572
Epoch 33, Loss: 0.2539
Epoch 34, Loss: 0.2506
Epoch 35, Loss: 0.2474
Epoch 36, Loss: 0.2442
Epoch 37, Loss: 0.2410
Epoch 38, Loss: 0.2379
Epoch 39, Loss: 0.2348
Epoch 40, Loss: 0.2317
Epoch 41, Loss: 0.2287
Epoch 42, Loss: 0.2258
Epoch 43, Loss: 0.2229
Epoch 44, Loss: 0.22

In [260]:
output_layer

array([0.0021531 , 0.00204774, 0.77721847, 0.00196863, 0.00206441,
       0.00208411, 0.00199064, 0.00218223, 0.20627317, 0.0020175 ])

## Testing

In [267]:
test_image = np.array([
        [1, 1, 1, 1, 1],
        [0, 0, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 0, 0],
        [1, 1, 1, 1, 1]
    ])

true_label = np.array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [268]:
# Forward Pass for Testing
feature_map  = conv2d(test_image, kernel)
activated    = relu(feature_map)
pooled       = max_pooling(activated, pool_size=2)
flattened    = pooled.flatten()
dense_output = dense_layer(flattened, fc_weights, fc_bias)
output_layer = softmax(dense_output)

# Predicted class
predicted_label = np.argmax(output_layer)
true_class = np.argmax(true_label)

print("Predicted Class:", predicted_label)
print("True Class:", true_class)
print("Output Probabilities:", output_layer)

Predicted Class: 2
True Class: 2
Output Probabilities: [5.16254350e-04 4.43114414e-04 7.88553716e-01 4.31629893e-04
 4.61064763e-04 4.84853241e-04 4.54236329e-04 5.16126405e-04
 2.07675228e-01 4.63776768e-04]


In [269]:
print("Expected Label:", true_label)
print("Predicted Probabilities:", output_layer)
print("Argmax of True Label:", np.argmax(true_label))

Expected Label: [0 0 1 0 0 0 0 0 0 0]
Predicted Probabilities: [5.16254350e-04 4.43114414e-04 7.88553716e-01 4.31629893e-04
 4.61064763e-04 4.84853241e-04 4.54236329e-04 5.16126405e-04
 2.07675228e-01 4.63776768e-04]
Argmax of True Label: 2
